import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["700", "400"],
});

export const metadata = {
  title: "Link Sharing App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${instrumentSans.className} bg-main-bg px-6 py-4`}>
        {children}
      </body>
    </html>
  );
}
